In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
import statsmodels.api as sm
import seaborn as sns
import bambi as bmb
import arviz as az

pa_gs = pd.read_csv('data/pa_data.csv')
temps = pd.read_csv("data/pa_temps_supplement.csv")
#combining main csv dataset with supplementary temperature data csv
pa_gs = pa_gs.merge(temps, on=["station_id", "year"], how="left")

#limiting dataset to just time interval of interest
pa_gs = pa_gs[pa_gs['year'] >= 1960]

In [18]:
pa_gs_yr_gsl = pa_gs[['year', 'growing_season_length', 'station_id']]
pa_gs_non_gsl = pa_gs.drop(['growing_season_length'], axis = 1)

In [19]:
pa_gs_lagged = pa_gs_non_gsl.copy(deep=True)
pa_gs_lagged['year'] += 1

In [20]:
pa_gs_non_gsl.head(5)

,station_id,year,last_spring_frost_doy,last_spring_frost_date,first_fall_frost_doy,first_fall_frost_date,dtr_annual,dtr_spring,dtr_summer,tmax_annual,...,cloud_cover_pennsylvania,evaporation_pennsylvania,dewpoint_station,soil_moisture_station,cloud_cover_station,evaporation_station,tmean_spring,tmean_april,tmean_fall,tmean_october
0,USC00360022,2011,97,2011-04-07,301,2011-10-28,10.472299,11.314444,12.800000,16.367313,...,0.643602,1.986064,6.147552,0.457306,0.665281,2.143988,10.148333,10.916071,12.314286,11.000000
1,USC00360022,2012,88,2012-03-28,287,2012-10-13,9.794857,11.177174,9.884783,18.096571,...,0.594570,1.912246,5.980743,0.431833,0.587725,1.938779,13.512500,9.955000,12.115000,11.946774
2,USC00360022,2013,135,2013-05-15,301,2013-10-28,10.373088,11.328571,12.740244,15.384136,...,0.640574,1.798304,4.794067,0.441306,0.678640,1.894341,9.203846,10.683333,11.280220,12.712903
3,USC00360022,2014,115,2014-04-25,307,2014-11-03,9.648923,11.374419,10.137838,13.783692,...,0.645570,1.872335,4.093048,0.454242,0.673488,2.092208,8.120930,9.065000,10.852381,12.476667
4,USC00360022,2015,93,2015-04-03,292,2015-10-19,9.443731,10.935556,9.436471,16.000612,...,0.641373,1.805471,5.336334,0.437924,0.658836,1.886143,9.212222,10.750000,13.650610,11.162069

In [21]:
pa_gs_lagged.head(5)

,station_id,year,last_spring_frost_doy,last_spring_frost_date,first_fall_frost_doy,first_fall_frost_date,dtr_annual,dtr_spring,dtr_summer,tmax_annual,...,cloud_cover_pennsylvania,evaporation_pennsylvania,dewpoint_station,soil_moisture_station,cloud_cover_station,evaporation_station,tmean_spring,tmean_april,tmean_fall,tmean_october
0,USC00360022,2012,97,2011-04-07,301,2011-10-28,10.472299,11.314444,12.800000,16.367313,...,0.643602,1.986064,6.147552,0.457306,0.665281,2.143988,10.148333,10.916071,12.314286,11.000000
1,USC00360022,2013,88,2012-03-28,287,2012-10-13,9.794857,11.177174,9.884783,18.096571,...,0.594570,1.912246,5.980743,0.431833,0.587725,1.938779,13.512500,9.955000,12.115000,11.946774
2,USC00360022,2014,135,2013-05-15,301,2013-10-28,10.373088,11.328571,12.740244,15.384136,...,0.640574,1.798304,4.794067,0.441306,0.678640,1.894341,9.203846,10.683333,11.280220,12.712903
3,USC00360022,2015,115,2014-04-25,307,2014-11-03,9.648923,11.374419,10.137838,13.783692,...,0.645570,1.872335,4.093048,0.454242,0.673488,2.092208,8.120930,9.065000,10.852381,12.476667
4,USC00360022,2016,93,2015-04-03,292,2015-10-19,9.443731,10.935556,9.436471,16.000612,...,0.641373,1.805471,5.336334,0.437924,0.658836,1.886143,9.212222,10.750000,13.650610,11.162069

In [25]:
pa_gs_lagged_vars = pa_gs_lagged.merge(pa_gs_yr_gsl, on=["station_id", "year"], how = "left")

In [26]:
pa_gs_lagged_vars.head(5)

,station_id,year,last_spring_frost_doy,last_spring_frost_date,first_fall_frost_doy,first_fall_frost_date,dtr_annual,dtr_spring,dtr_summer,tmax_annual,...,evaporation_pennsylvania,dewpoint_station,soil_moisture_station,cloud_cover_station,evaporation_station,tmean_spring,tmean_april,tmean_fall,tmean_october,growing_season_length
0,USC00360022,2012,97,2011-04-07,301,2011-10-28,10.472299,11.314444,12.800000,16.367313,...,1.986064,6.147552,0.457306,0.665281,2.143988,10.148333,10.916071,12.314286,11.000000,199.0
1,USC00360022,2013,88,2012-03-28,287,2012-10-13,9.794857,11.177174,9.884783,18.096571,...,1.912246,5.980743,0.431833,0.587725,1.938779,13.512500,9.955000,12.115000,11.946774,166.0
2,USC00360022,2014,135,2013-05-15,301,2013-10-28,10.373088,11.328571,12.740244,15.384136,...,1.798304,4.794067,0.441306,0.678640,1.894341,9.203846,10.683333,11.280220,12.712903,192.0
3,USC00360022,2015,115,2014-04-25,307,2014-11-03,9.648923,11.374419,10.137838,13.783692,...,1.872335,4.093048,0.454242,0.673488,2.092208,8.120930,9.065000,10.852381,12.476667,199.0
4,USC00360022,2016,93,2015-04-03,292,2015-10-19,9.443731,10.935556,9.436471,16.000612,...,1.805471,5.336334,0.437924,0.658836,1.886143,9.212222,10.750000,13.650610,11.162069,212.0

In [38]:
def remove_nulls_simple(data_subset, variables):
        # Drop rows where any of the specified variable columns have nulls
        data_subset_cleaned = data_subset.dropna(subset=variables, ignore_index=True)
        # Subsets the cleaned dataframe back into only chosen variables
        vars_cleaned = data_subset_cleaned[variables]
        return vars_cleaned

def list_to_str(list_name):
    string = " + ".join(list_name)
    return string
    
def bayesian_model_unstandardized(data, target_var_name, cov_list):

    cov_str = list_to_str(cov_list)
    cov_list_target_var = list(cov_list) + [target_var_name] + ['year']
    data = remove_nulls_simple(data, cov_list_target_var)
    
    formula = bmb.Formula(f"{target_var_name} ~ {cov_str} + year",
                      f"sigma ~ {cov_str} + year")
    model = bmb.Model(formula, data=data, dropna = True)
    output = model.fit(idata_kwargs={'log_likelihood':True})

    resid = data[target_var_name] - model.predict(output, inplace=False).posterior["mu"].mean(("chain", "draw")).values
    
    return model, output, resid


all_covs_list = ['dtr_annual', 'dtr_spring', 'tmean_spring','tmean_fall','latitude','longitude','tmax_annual','oni_annual',
                'nao_annual','pna_annual','amo_annual','sst_north_atlantic','pwat_station','dewpoint_station',
                'soil_moisture_station','cloud_cover_station','evaporation_station',
                'sst_gulf_mexico','pwat_southeast_us','dewpoint_2m_southeast_us','soil_moisture_southeast_us',
                'cloud_cover_southeast_us','evaporation_southeast_us']

In [39]:
lagged_model, lagged_output, lagged_resid = bayesian_model_unstandardized(pa_gs_lagged_vars, 'growing_season_length', all_covs_list)

                                                             Grad
  Progress               Draw        Divergen…   Step size   evals       Speed                Elapsed    Remaini…
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  ━━━━━━━━━━━━━━━━━━━━   2000        0           0.121       31          142.55 draws/s       0:00:14    0:00:00
  ━━━━━━━━━━━━━━━━━━━━   2000        0           0.176       31          108.09 draws/s       0:00:18    0:00:00
  ━━━━━━━━━━━━━━━━━━━━   2000        0           0.150       31          137.20 draws/s       0:00:14    0:00:00
  ━━━━━━━━━━━━━━━━━━━━   2000        0           0.126       31          105.25 draws/s       0:00:18    0:00:00

/home/reu/.venv/lib/python3.14/site-packages/pymc/sampling/mcmc.py:1163: FutureWarning: Passing `log_likelihood` via `idata_kwargs` is deprecated and will be removed in future versions. Call `pm.compute_log_likelihood(idata)` instead.
  return _sample_return(
Sampling 4 chains for 1_000 tune and 1_000 draw iterations (4_000 + 4_000 draws total) took 25 seconds.

In [40]:
az.summary(lagged_output)

,mean,sd,eti89_lb,eti89_ub,ess_bulk,ess_tail,r_hat,mcse_mean,mcse_sd
Intercept,-137,77,-260,-15,2621,2760,1.00,1.5,1.2
dtr_annual,-11.99,0.49,-13,-11,2670,2942,1.00,0.0095,0.0068
dtr_spring,1.32,0.362,0.74,1.9,3716,3277,1.00,0.0059,0.0042
tmean_spring,0.01,0.302,-0.48,0.49,3210,2985,1.00,0.0053,0.0037
tmean_fall,3.262,0.303,2.8,3.7,4084,3365,1.00,0.0047,0.0034
latitude,-4.55,0.66,-5.6,-3.5,3707,3165,1.00,0.011,0.0076
longitude,1.965,0.222,1.6,2.3,3505,2970,1.00,0.0037,0.0026
tmax_annual,7.1,0.51,6.3,7.9,2901,3102,1.00,0.0095,0.0069
oni_annual,5.18,0.54,4.3,6,5000,3623,1.00,0.0076,0.0055
nao_annual,10.89,0.92,9.4,12,3836,3080,1.00,0.015,0.011
pna_annual,-4.87,0.92,-6.4,-3.4,6681,3372,1.00,0.011,0.0079
amo_annual,-0.9,3.74,-6.8,5.1,3498,3344,1.00,0.063,0.045
sst_north_atlantic,9.9,3.44,4.3,15,2750,2879,1.00,0.066,0.049
pwat_station,-3.44,0.323,-3.9,-2.9,3939,3435,1.00,0.0051,0.0037
dewpoint_station,0.64,0.6,-0.33,1.6,2741,2800,1.00,0.012,0.0082
soil_moisture_station,-31.4,8,-44,-18,5064,3099,1.00,0.11,0.082
cloud_cover_station,-4.8,10.2,-21,11,3021,3211,1.00,0.19,0.13
evaporation_station,2.89,1.72,0.09,5.7,4761,3254,1.00,0.025,0.017
sst_gulf_mexico,1.23,2.18,-2.2,4.7,2156,2489,1.00,0.047,0.034
pwat_southeast_us,1.2,0.58,0.26,2.1,3498,2885,1.00,0.0099,0.007
dewpoint_2m_southeast_us,-14.19,1.41,-16,-12,1930,2343,1.00,0.032,0.023
soil_moisture_southeast_us,526,92,380,670,2481,2935,1.00,1.9,1.3
cloud_cover_southeast_us,-63.5,19.5,-94,-33,2689,2606,1.00,0.38,0.27
evaporation_southeast_us,-1.3,3.12,-6.3,3.6,3393,3082,1.00,0.053,0.038
year,0.287,0.041,0.22,0.35,3189,3285,1.00,0.00073,0.00051
sigma_Intercept,21.92,2.75,18,26,4111,3532,1.00,0.043,0.029
sigma_dtr_annual,0.0689,0.0187,0.04,0.099,2454,2714,1.00,0.00038,0.00028
sigma_dtr_spring,-0.0089,0.0138,-0.031,0.013,3315,3077,1.00,0.00024,0.00017
sigma_tmean_spring,0.0497,0.0113,0.032,0.068,3437,3178,1.00,0.00019,0.00013
sigma_tmean_fall,-0.0201,0.0113,-0.038,-0.0019,4032,3266,1.00,0.00018,0.00013
sigma_latitude,-0.0301,0.0258,-0.071,0.011,4619,3270,1.00,0.00038,0.00026
sigma_longitude,0.015,0.0091,0.00082,0.029,3371,3180,1.00,0.00016,0.00011
sigma_tmax_annual,-0.0754,0.0195,-0.11,-0.045,2865,3036,1.00,0.00036,0.00026
sigma_oni_annual,0.0246,0.0205,-0.0078,0.057,3933,2869,1.00,0.00033,0.00023
sigma_nao_annual,-0.022,0.0378,-0.083,0.038,5654,3626,1.00,0.0005,0.00036
sigma_pna_annual,0.054,0.0387,-0.0072,0.12,5824,3256,1.00,0.00051,0.00035
sigma_amo_annual,0.126,0.174,-0.15,0.4,3081,2988,1.00,0.0031,0.0022
sigma_sst_north_atlantic,-0.094,0.155,-0.34,0.16,2939,2820,1.00,0.0029,0.0019
sigma_pwat_station,0.0154,0.0141,-0.0073,0.038,3187,3094,1.00,0.00025,0.00018
sigma_dewpoint_station,0.052,0.0252,0.011,0.092,2441,3047,1.00,0.00051,0.00035
sigma_soil_moisture_station,-0.276,0.317,-0.79,0.24,5018,3295,1.00,0.0045,0.0032
sigma_cloud_cover_station,0.99,0.38,0.37,1.6,3099,2980,1.00,0.0069,0.005
sigma_evaporation_station,0.09,0.069,-0.02,0.2,5689,3272,1.00,0.00091,0.00063
sigma_sst_gulf_mexico,-0.058,0.073,-0.17,0.058,4204,3073,1.00,0.0011,0.00079
sigma_pwat_southeast_us,0.0258,0.0226,-0.011,0.062,3106,3055,1.00,0.00041,0.00029
sigma_dewpoint_2m_southeast_us,-0.024,0.051,-0.11,0.057,2445,3065,1.00,0.001,0.00073
sigma_soil_moisture_southeast_us,0.13,0.98,-1.4,1.7,7416,3389,1.00,0.011,0.0078
sigma_cloud_cover_southeast_us,-0.54,0.54,-1.4,0.34,4131,3382,1.00,0.0084,0.0059
sigma_evaporation_southeast_us,-0.165,0.11,-0.34,0.0071,5245,3230,1.00,0.0015,0.0011
sigma_year,-0.00678,0.00172,-0.0095,-0.004,3144,3246,1.00,3.1e-05,2.1e-05

#### Analysis of Model (Notable Findings)
* inc of 1 degree to previous year annual DTR indicates 11.99 day decrease to current year GSL --> up from current year DTR coefficient of 9.51 day decrease
    * what would the logical cause of the ~2.5 unit increase in coefficient between current year DTR and lagged prior year DTR?
    * Is DTR predictive, or is this an artifact of general GSL increase year over year?
        * year over year GSL increase from main un-lagged model is 0.21 days/yr increase, so does not explain full 2.5 unit change to coefficient (let alone the fact that this year over year change in GSL would be going against the magnitude of the DTR influence
* inc of 1 degree to previous year annual DTR indicates 7.1329% increase to GSLV
* inc of 1 degree to previous year tmean spring indicates 5.096% increase to GSLV
* inc of 1 degree to previous year tmean fall indicates 1.9899% decrease to GSLV
* inc of 1 degree to previous year annual mean tmax indicates 7.263% decrease to GSLV
    * how does this relate to the finding on Annual DTR and GSLV? Does annual DTR increase only increase GSLV if the increase in DTR is found at the bottom of the DTR range, rather than the top?