# Week 7 Report

**Date:** 2026-07-05 to 2026-07-10

## Goals for this week

- [ ] Complete analysis & compile results
- [ ] Begin Poster
- [ ] Begin Paper Draft

## What I did

After running my GSL model and DTR models both in full and just based on year and compiling the results, it became quickly apparent that I would need to run some smaller subset models to better identify what might be responsible for certain changes to mean of response and variance of response coefficients between models. In doing so, further results became apparent-- of which some made sense logically and some remain without a logical explanation. 

For example, running a DTR model based only on year found that variance in DTR has decreased 27.79% from 1960 to present, but running a DTR model with all 21 non-DTR coefficients included in the GSL model indicates that DTR variance has increased 77.6% in that same time period. Additionally, models with subsets of coefficients (grouped as climate indices, atmospheric/oceanic data, and temperature data) all find a decrease in variability, and models with specifically only year and one covariate from the list also all find a decrease in variability. Further testing may be necessary if we wish to explore this result further, though a brief foray into combining small sets of covariates from different subset groups (i.e. two covariates from the climate indices group with two covariates from the temperature data group) also failed to recreate the positive variability trend found in the full model.

However, on the whole, most of the results appear sound and have logical backing. Since compiling the results, I have successfully either shown that given results prove a hypothesis of ours, or been able to find published literature with a likely explanation for results unexpected by our hypotheses. A list of results can be found below in the "Results and figures" section.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import bambi as bmb
import arviz as az

def remove_nulls_simple(data_subset, variables):
        # Drop rows where any of the specified variable columns have nulls
        data_subset_cleaned = data_subset.dropna(subset=variables, ignore_index=True)
        # Subsets the cleaned dataframe back into only chosen variables
        vars_cleaned = data_subset_cleaned[variables]
        return vars_cleaned

def list_to_str(list_name):
    string = " + ".join(list_name)
    return string

pa_gs = pd.read_csv('/home/reu/project/data/pa_data.csv')
temps = pd.read_csv('/home/reu/project/data/pa_temps_supplement.csv')
pa_gs = pa_gs.merge(temps, on=["station_id", "year"], how="left")

pa_gs = pa_gs[pa_gs['year'] >= 1960]
pa_gs = pa_gs.drop(['station_id', 'last_spring_frost_date', 'first_fall_frost_date', 'station_name','state'], axis=1)

def bayesian_model_unstandardized(data, target_var_name, cov_list):

    cov_str = list_to_str(cov_list)
    cov_list_target_var = list(cov_list) + [target_var_name] + ['year']
    data = remove_nulls_simple(data, cov_list_target_var)
    
    formula = bmb.Formula(f"{target_var_name} ~ {cov_str} + year",
                      f"sigma ~ {cov_str} + year")
    model = bmb.Model(formula, data=data, dropna = True)
    output = model.fit(idata_kwargs={'log_likelihood':True})

    resid = data[target_var_name] - model.predict(output, inplace=False).posterior["mu"].mean(("chain", "draw")).values
    
    return model, output, resid

gsl_all_cov_list = ['dtr_annual','tmean_spring','tmean_fall','latitude','longitude','tmax_annual','oni_annual',
                'nao_annual','pna_annual','amo_annual','sst_north_atlantic','pwat_station','dewpoint_station',
                'soil_moisture_station','cloud_cover_station','evaporation_station', 'dtr_spring',
                'sst_gulf_mexico','pwat_southeast_us','dewpoint_2m_southeast_us','soil_moisture_southeast_us',
                'cloud_cover_southeast_us','evaporation_southeast_us']

dtr_all_cov_list = ['tmean_spring','tmean_fall','latitude','longitude','tmax_annual','oni_annual',
                'nao_annual','pna_annual','amo_annual','sst_north_atlantic','pwat_station','dewpoint_station',
                'soil_moisture_station','cloud_cover_station','evaporation_station',
                'sst_gulf_mexico','pwat_southeast_us','dewpoint_2m_southeast_us','soil_moisture_southeast_us',
                'cloud_cover_southeast_us','evaporation_southeast_us']

## Analysis

*(Add code and markdown cells as needed.)*

In [3]:
gsl_model, gsl_output, gsl_resid = bayesian_model_unstandardized(pa_gs, 'growing_season_length', gsl_all_cov_list)
az.summary(gsl_output).head(50)

                                                             Grad
  Progress               Draw        Divergen…   Step size   evals       Speed                Elapsed    Remaini…
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  ━━━━━━━━━━━━━━━━━━━━   2000        0           0.131       63          117.56 draws/s       0:00:17    0:00:00
  ━━━━━━━━━━━━━━━━━━━━   2000        0           0.167       31          111.19 draws/s       0:00:17    0:00:00
  ━━━━━━━━━━━━━━━━━━━━   2000        0           0.147       31          94.36 draws/s        0:00:21    0:00:00
  ━━━━━━━━━━━━━━━━━━━━   2000        0           0.159       31          107.76 draws/s       0:00:18    0:00:00

/home/reu/.venv/lib/python3.14/site-packages/pymc/sampling/mcmc.py:1163: FutureWarning: Passing `log_likelihood` via `idata_kwargs` is deprecated and will be removed in future versions. Call `pm.compute_log_likelihood(idata)` instead.
  return _sample_return(
Sampling 4 chains for 1_000 tune and 1_000 draw iterations (4_000 + 4_000 draws total) took 27 seconds.

,mean,sd,eti89_lb,eti89_ub,ess_bulk,ess_tail,r_hat,mcse_mean,mcse_sd
Intercept,127,68,18,240,2777,3143,1.00,1.3,0.94
dtr_annual,-9.52,0.44,-10,-8.8,2982,3124,1.00,0.0081,0.0057
tmean_spring,1.235,0.27,0.81,1.7,3684,3100,1.00,0.0044,0.0031
tmean_fall,5.753,0.278,5.3,6.2,3515,3323,1.00,0.0047,0.0033
latitude,-2.58,0.6,-3.5,-1.6,3691,3197,1.00,0.0098,0.0069
longitude,1.407,0.203,1.1,1.7,3255,3115,1.00,0.0036,0.0025
tmax_annual,3.63,0.46,2.9,4.4,3060,3130,1.00,0.0083,0.0059
oni_annual,0.11,0.51,-0.7,0.92,4756,3396,1.00,0.0074,0.0053
nao_annual,0.32,0.82,-1,1.7,3605,3033,1.00,0.014,0.0094
pna_annual,2.22,0.88,0.8,3.6,4723,3194,1.00,0.013,0.0091
amo_annual,3.5,3.59,-2.2,9.1,3285,3171,1.00,0.063,0.046
sst_north_atlantic,-3.2,3.3,-8.5,2,2395,2588,1.00,0.068,0.05
pwat_station,-1.395,0.295,-1.9,-0.92,4055,3309,1.00,0.0046,0.0032
dewpoint_station,-0.99,0.56,-1.9,-0.12,2967,3100,1.00,0.01,0.0072
soil_moisture_station,2,7.3,-9.7,14,4538,3172,1.00,0.11,0.075
cloud_cover_station,-27.6,9.6,-43,-12,3433,2906,1.00,0.16,0.11
evaporation_station,4.63,1.58,2,7.1,4889,3543,1.00,0.023,0.016
dtr_spring,-0.21,0.331,-0.74,0.31,4245,3384,1.00,0.0051,0.0036
sst_gulf_mexico,0.57,2.03,-2.6,3.8,2447,3000,1.00,0.041,0.03
pwat_southeast_us,2.14,0.54,1.3,3,3453,3429,1.00,0.0091,0.0066
dewpoint_2m_southeast_us,-4.29,1.27,-6.3,-2.3,2348,2717,1.00,0.026,0.018
soil_moisture_southeast_us,141,84,10,280,3061,3030,1.00,1.5,1.1
cloud_cover_southeast_us,-120.3,18.1,-150,-92,2942,2720,1.00,0.34,0.24
evaporation_southeast_us,-13.85,2.78,-18,-9.4,3548,3302,1.00,0.047,0.032
year,0.211,0.038,0.15,0.27,2780,2954,1.00,0.00072,0.00053
sigma_Intercept,10.68,2.76,6.4,15,3934,3509,1.00,0.044,0.031
sigma_dtr_annual,0.1227,0.0188,0.092,0.15,2494,2704,1.00,0.00038,0.00026
sigma_tmean_spring,0.029,0.0109,0.012,0.046,3194,2942,1.00,0.00019,0.00014
sigma_tmean_fall,0.0136,0.0108,-0.0035,0.031,3637,3138,1.00,0.00018,0.00013
sigma_latitude,0.0033,0.0252,-0.036,0.045,4642,3094,1.00,0.00037,0.00026
sigma_longitude,-0.0192,0.0089,-0.033,-0.0048,3743,3105,1.00,0.00015,0.0001
sigma_tmax_annual,-0.056,0.0185,-0.086,-0.027,2619,2703,1.00,0.00036,0.00025
sigma_oni_annual,0.0262,0.0206,-0.0067,0.059,4875,3161,1.00,0.00029,0.00021
sigma_nao_annual,0.042,0.0356,-0.016,0.1,4329,3024,1.00,0.00054,0.00038
sigma_pna_annual,0.0614,0.0363,0.0036,0.12,5682,3311,1.00,0.00048,0.00035
sigma_amo_annual,0.096,0.18,-0.19,0.37,3258,3068,1.00,0.0032,0.0023
sigma_sst_north_atlantic,0.106,0.159,-0.14,0.36,2851,2890,1.00,0.003,0.0021
sigma_pwat_station,0.0087,0.0133,-0.013,0.03,3675,3082,1.00,0.00022,0.00016
sigma_dewpoint_station,-0.0312,0.0247,-0.07,0.0086,2577,2665,1.00,0.00049,0.00035
sigma_soil_moisture_station,-0.076,0.297,-0.55,0.4,5395,3078,1.00,0.004,0.0028
sigma_cloud_cover_station,0.01,0.374,-0.59,0.6,3548,3222,1.00,0.0063,0.0044
sigma_evaporation_station,-0.002,0.067,-0.11,0.1,4302,2896,1.00,0.001,0.00076
sigma_dtr_spring,-0.0638,0.0138,-0.086,-0.041,3066,2666,1.00,0.00025,0.00018
sigma_sst_gulf_mexico,-0.101,0.078,-0.23,0.025,2820,2805,1.00,0.0015,0.001
sigma_pwat_southeast_us,-0.0236,0.0222,-0.059,0.012,3578,3191,1.00,0.00037,0.00026
sigma_dewpoint_2m_southeast_us,0.062,0.05,-0.016,0.14,2363,2593,1.00,0.001,0.00073
sigma_soil_moisture_southeast_us,-0.88,0.96,-2.4,0.63,6466,2924,1.00,0.012,0.0085
sigma_cloud_cover_southeast_us,1.31,0.54,0.43,2.2,3692,3117,1.00,0.0089,0.0062
sigma_evaporation_southeast_us,-0.145,0.1,-0.31,0.015,4553,3478,1.00,0.0015,0.001
sigma_year,-0.00474,0.00164,-0.0074,-0.0021,3329,3035,1.00,2.8e-05,2e-05

In [4]:
dtr_model, dtr_output, dtr_resid = bayesian_model_unstandardized(pa_gs, 'dtr_annual', dtr_all_cov_list)
az.summary(dtr_output).head(50)

                                                             Grad
  Progress               Draw        Divergen…   Step size   evals       Speed                Elapsed    Remaini…
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  ━━━━━━━━━━━━━━━━━━━━   2000        0           0.208       63          151.22 draws/s       0:00:13    0:00:00
  ━━━━━━━━━━━━━━━━━━━━   2000        0           0.119       31          153.40 draws/s       0:00:13    0:00:00
  ━━━━━━━━━━━━━━━━━━━━   2000        0           0.164       31          95.90 draws/s        0:00:20    0:00:00
  ━━━━━━━━━━━━━━━━━━━━   2000        0           0.148       31          151.82 draws/s       0:00:13    0:00:00

/home/reu/.venv/lib/python3.14/site-packages/pymc/sampling/mcmc.py:1163: FutureWarning: Passing `log_likelihood` via `idata_kwargs` is deprecated and will be removed in future versions. Call `pm.compute_log_likelihood(idata)` instead.
  return _sample_return(
Sampling 4 chains for 1_000 tune and 1_000 draw iterations (4_000 + 4_000 draws total) took 26 seconds.

,mean,sd,eti89_lb,eti89_ub,ess_bulk,ess_tail,r_hat,mcse_mean,mcse_sd
Intercept,2.4,2.9,-2.2,7.1,3433,3066,1.00,0.05,0.035
tmean_spring,-0.5458,0.0106,-0.56,-0.53,4285,3364,1.00,0.00016,0.00012
tmean_fall,-0.5979,0.0103,-0.61,-0.58,4662,3482,1.00,0.00015,0.0001
latitude,0.0785,0.0276,0.035,0.12,5050,3220,1.00,0.00039,0.00027
longitude,-0.1301,0.0089,-0.14,-0.12,3498,3257,1.00,0.00015,0.0001
tmax_annual,1.3237,0.0139,1.3,1.3,4028,3403,1.00,0.00022,0.00015
oni_annual,0.067,0.0221,0.032,0.1,4206,3503,1.00,0.00034,0.00024
nao_annual,-0.215,0.0373,-0.27,-0.16,4003,3154,1.00,0.00059,0.00041
pna_annual,0.036,0.0422,-0.031,0.1,4831,2981,1.00,0.00061,0.00045
amo_annual,1.871,0.133,1.7,2.1,3940,3240,1.00,0.0021,0.0015
sst_north_atlantic,-2.135,0.134,-2.3,-1.9,2497,2749,1.00,0.0027,0.0019
pwat_station,0.1319,0.0132,0.11,0.15,4033,3357,1.00,0.00021,0.00015
dewpoint_station,-0.554,0.0249,-0.59,-0.51,2263,2304,1.00,0.00052,0.00037
soil_moisture_station,3.15,0.343,2.6,3.7,4938,3446,1.00,0.0049,0.0033
cloud_cover_station,-2.04,0.43,-2.7,-1.3,2960,3131,1.00,0.008,0.0056
evaporation_station,0.377,0.075,0.26,0.5,4933,3490,1.00,0.0011,0.00075
sst_gulf_mexico,0.618,0.092,0.47,0.77,2265,2655,1.00,0.0019,0.0013
pwat_southeast_us,-0.0335,0.024,-0.071,0.006,2543,2736,1.00,0.00047,0.00033
dewpoint_2m_southeast_us,-0.058,0.065,-0.17,0.043,1550,2210,1.01,0.0016,0.0011
soil_moisture_southeast_us,-10.8,3.9,-17,-4.6,2531,2998,1.00,0.077,0.056
cloud_cover_southeast_us,-0.36,0.78,-1.6,0.88,2754,3000,1.00,0.015,0.011
evaporation_southeast_us,-0.073,0.138,-0.3,0.15,3057,3181,1.00,0.0025,0.0018
year,0.00969,0.00165,0.0071,0.012,2863,2977,1.00,3.1e-05,2.2e-05
sigma_Intercept,8.06,2.54,4.1,12,4678,3621,1.00,0.037,0.026
sigma_tmean_spring,0.0348,0.0086,0.021,0.048,4709,2986,1.00,0.00013,8.7e-05
sigma_tmean_fall,0.0262,0.0087,0.012,0.04,5530,3319,1.00,0.00012,8.4e-05
sigma_latitude,0.0064,0.0246,-0.032,0.046,5083,3310,1.00,0.00035,0.00024
sigma_longitude,0.0156,0.0085,0.0022,0.029,3688,2946,1.00,0.00014,9.8e-05
sigma_tmax_annual,-0.056,0.01,-0.072,-0.04,4631,3442,1.00,0.00015,0.0001
sigma_oni_annual,0.1329,0.0207,0.099,0.17,4897,3536,1.00,0.0003,0.0002
sigma_nao_annual,0.0196,0.0356,-0.036,0.078,6184,3180,1.00,0.00045,0.00031
sigma_pna_annual,-0.352,0.0404,-0.42,-0.29,5585,3754,1.00,0.00054,0.00039
sigma_amo_annual,0.649,0.167,0.38,0.91,3268,3398,1.00,0.0029,0.002
sigma_sst_north_atlantic,-0.934,0.157,-1.2,-0.68,2587,2857,1.00,0.0031,0.0022
sigma_pwat_station,-0.0244,0.0129,-0.045,-0.0034,4396,3321,1.00,0.00019,0.00014
sigma_dewpoint_station,0.1113,0.0235,0.074,0.15,2927,2961,1.00,0.00043,0.00032
sigma_soil_moisture_station,-0.083,0.301,-0.57,0.41,6438,3007,1.00,0.0038,0.0026
sigma_cloud_cover_station,1.93,0.387,1.3,2.5,3221,3226,1.00,0.0068,0.0048
sigma_evaporation_station,0.205,0.07,0.092,0.32,5401,3514,1.00,0.00095,0.00066
sigma_sst_gulf_mexico,-0.124,0.08,-0.25,0.0032,3132,3312,1.00,0.0014,0.001
sigma_pwat_southeast_us,0.125,0.0237,0.087,0.16,3231,3366,1.00,0.00042,0.0003
sigma_dewpoint_2m_southeast_us,-0.447,0.053,-0.53,-0.36,2535,2952,1.00,0.0011,0.00072
sigma_soil_moisture_southeast_us,0.32,0.97,-1.2,1.9,7795,2957,1.00,0.011,0.0079
sigma_cloud_cover_southeast_us,-2.4,0.55,-3.3,-1.5,5136,3128,1.00,0.0076,0.0054
sigma_evaporation_southeast_us,0.25,0.11,0.075,0.43,5499,3116,1.00,0.0015,0.0011
sigma_year,0.00885,0.00165,0.0061,0.011,3098,3235,1.00,3e-05,2.1e-05

## Results and figures

*(Summarize key findings. Include any plots you made.)*

Models
* 1 - GSL modeled by DTR and Year Only
* 2 - GSL modeled by DTR, Year, and Mean Temperatures
* 3 - GSL modeled by DTR, Year, Mean Temps, and Max Temps
* 4 - GSL modeled by all 17 covariates
* 5 - Annual DTR modeled by Year only
* 6 - Annual DTR modeled by all 15 non-DTR covariates

Re-defining Trends in GSL and DTR
GSL
* Model 4 showed GSL as increasing at 0.21 days/yr ( +/- 0.038 days ? standard deviation)

DTR
* Model 5 (yr) showed DTR as decreasing at 0.012 deg C/yr
* Model 6 (yr w/cov) showed DTR as increasing at 0.009  deg C/yr
    * Not a single clue why this is the case
    * Modeled every single covariate individually and every single one showed a decrease in DTR

Defining direct impact of Annual DTR on GSL
* Model 4 associated a 1 degree increase in DTR with a 9.51 day reduction in growing season (+/- 0.46 days ? standard deviation)

GSL Variance
* Model 4 indicated a 26.7543% (+/- 8.24%? Standard Deviation) decrease in GSL Variability from 1960 to 2025 (Model 2 indicated 26.42% decrease, Model 1 indicated a 31.41% decrease)
* Model 4 indicated a 2.963% increase in GSL variability for 1 degree celsius increase in Mean Spring Temperature
    * Per standard deviation: 5.94% increase
    * Opposite of hypothesized expectation based on previous finding of less temperature variability when mean is higher
    * An increase in mean spring temperature in PA likely indicates an increase in mean spring temperature across much of the Northern Hemisphere/world → Arctic warming increases the frequency of both extreme cold and extreme snow events in the midlatitudes → anomalously warm arctic in the spring = more variable temperatures across PA in the spring → more variable GSL?
* Model 4 indicated a 1.39% decrease in GSL variability for each unit of longitude traveled West
    * Impact of ocean? If so, why would SST covariate not be significant at 95%?
* Model 4 indicated a 5.456% decrease in GSL variability for each 1 degree celsius increase in tmax_annual
    * Per standard deviation: 9.53% decrease
    * This does conform with expectation that higher temperatures mean less temperature variability
* Model 4 indicated a 13.066% increase in GSL variability for every 1 degree C increase in dtr_annual
* Model 4 indicated a 7.42% increase in GSL variability for every 2.74% (1 standard deviation) increase in Southeast US Cloud Cover
    * US Northeast anomalous spring cold events occur when the Northern Hemisphere Jet stream is further to the south, and therefore passing to the north of or directly over the US Southeast. As the anomalous cold occurs over the Northeast (causing a decrease in growing season overall and an increase in variability through the unpredictability of anomalous events), low-pressure systems are likely to pass over the US Southeast along the jet stream, increasing overall cloud cover in the region and thus causing this connection in the model.

DTR Variance
* Model 5 indicated a 27.79% decrease in DTR variability from 1960 to 2025
* Model 6 indicated a 77.6% increase in same time period
    * Not a single clue why this is the case
    * Modeled every single covariate individually and every single one saw decrease in DTR variability

Consideration of Mean Temperature on Impact of DTR to GSL variability
* Model 1 indicated that without considering temperature, for every degree increase in DTR, GSL Variance decreases 4.171% (becomes more predictable)
* Model 2 indicated that with mean temperatures are considered, for every degree increase in DTR, GSL Variance increases 3.169% (becomes less predictable)
* Model 4 indicated that with all covariables considered, for every degree increase in DTR, GSL variance increases 13.0658% (becomes much less predictable)
* Ran a new model (Model 3) after noticing an increase in sigma_dtr_annual (variance of responses for Annual DTR) between exploratory standardized model runs not including Maximum Annual Temperature and including Maximum Annual Temperature
* Model 3 indicated that, with mean and max temperatures considered, for every degree increase in DTR, GSL Variance increases 4.739%

Discussion
* Hypothesis was that given a warming mean temperature, DTR and GSL variability would generally decrease, since warmer temperatures are less variable
* GSL variability is decreasing → results agree with hypothesis → explain logic
* DTR variability is all kinds of weird → all models other than model 6 (all covariates together) show decrease in variability, model 6 shows huge increase in variability
* Hypothesis was that increasing DTR would lower GSL variability → results do not match hypothesis → what logical reasoning could this align with?
* Hypothesis was that DTR’s impact on GSL would be heavily tied to mean temperatures → results agree with hypothesis, but in the opposite manner that we expected… restate results → discuss potential logical explanations
* Hypothesis was that larger DTRs have shorter GSL → results match hypothesis (1 deg inc in DTR = 9.5 day dec in GSL) → restate logic

## Questions and blockers

* Struggling to visualize the connection between temperature and DTR's impact on GSL variance as a plot
* Looking for feedback on poster/paper draft

## Plan for next week

- [ ] Finish Poster
- [ ] Continue Drafting Paper